// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheProject.Infrastructure.Data;

#nullable disable

namespace TheProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240410191711_SeedMoreStableMigration")]
    partial class SeedMoreStableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology and Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Business and Entrepreneurship"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Creative Arts and Design"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health and Wellness"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Environmental Science and Sustainability"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Engineering and Robotics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Language and Communication"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Data Science and Analytics"
                        },
                        new
                        {
                            Id = 9,
                            Name = "History and Culture"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Personal Development and Leadership"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interested")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            CategoryId = 1,
                            Description = "Learn to build scalable web applications using React, Node.js, Express, and MongoDB.",
                            EndDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://img-b.udemycdn.com/course/750x422/2715276_2923_2.jpg",
                            Interested = 120,
                            StartDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Full Stack Web Development"
                        },
                        new
                        {
                            Id = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            CategoryId = 1,
                            Description = "Dive into data science and machine learning with Python, exploring data visualization, machine learning models, and more.",
                            EndDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://media.geeksforgeeks.org/wp-content/uploads/20210629202956/DataV.png",
                            Interested = 150,
                            StartDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Science and Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            CategoryId = 2,
                            Description = "Master digital marketing tools and strategies, including SEO, PPC, social media, and content marketing.",
                            EndDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.redbricksmedia.com/wp-content/uploads/2023/04/What-are-the-Advantages-of-Digital-Marketing.jpg",
                            Interested = 90,
                            StartDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Digital Marketing Essentials"
                        },
                        new
                        {
                            Id = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            CategoryId = 3,
                            Description = "Explore the fundamentals of graphic design, including layout, composition, typography, and color theory.",
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.ytimg.com/vi/YqQx75OPRa0/maxresdefault.jpg",
                            Interested = 110,
                            StartDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            CategoryId = 2,
                            Description = "Prepare for the PMP certification exam with this comprehensive course covering project management best practices.",
                            EndDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://play-lh.googleusercontent.com/KO4qR1Yik54zkBEWKoVqbUtJqOAw2w6loHapeAaacDeBpy9lU7hM1fpNU-VN4kzRwpc",
                            Interested = 75,
                            StartDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Project Management Professional Certification Prep"
                        },
                        new
                        {
                            Id = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            CategoryId = 5,
                            Description = "An exploration of sustainable living practices including renewable energy, green building, and sustainable agriculture.",
                            EndDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://media.restless.co.uk/uploads/2021/04/13_tips_for_sustainable_living.jpg",
                            Interested = 65,
                            StartDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sustainable Living"
                        },
                        new
                        {
                            Id = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            CategoryId = 6,
                            Description = "Get hands-on experience building and programming your first robot using Arduino and Raspberry Pi.",
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://miro.medium.com/v2/resize:fit:960/1*o2QkJWlZWqtDa-g3luWT1Q.jpeg",
                            Interested = 80,
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Robotics"
                        },
                        new
                        {
                            Id = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            CategoryId = 7,
                            Description = "Learn Spanish from scratch! Master the basics of conversation, grammar, and vocabulary with this interactive course.",
                            EndDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://effortlessconversations.com/wp-content/uploads/2023/10/is-spanish-hard-learn-spanish-text-on-laptop-1024x683.jpg",
                            Interested = 95,
                            StartDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spanish for Beginners"
                        },
                        new
                        {
                            Id = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            CategoryId = 4,
                            Description = "Learn how to offer initial support to adults who are developing a mental health problem or experiencing a mental health crisis.",
                            EndDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://addictionstraininginstitute.com/wp-content/uploads/2023/05/image-26.png",
                            Interested = 70,
                            StartDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mental Health First Aid"
                        },
                        new
                        {
                            Id = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            CategoryId = 3,
                            Description = "Unlock your creative potential and discover how to craft compelling stories with character, plot, and heart.",
                            EndDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.artshub.com.au/wp-content/uploads/sites/2/2022/05/shutterstock_516275947-e1652150413730.jpg",
                            Interested = 85,
                            StartDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Creative Writing"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf3d6a40-d66d-4e7c-9709-bcaa5c199601"),
                            Bio = "Expert in full stack development with over 10 years of experience.",
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            FirstName = "Angelina",
                            LastName = "Jolie",
                            Photo = "https://i.pinimg.com/736x/b7/5b/49/b75b49e64989d5b5944c80f302228e2e.jpg"
                        },
                        new
                        {
                            Id = new Guid("8448aaa2-1ad0-4ed4-9566-d5e3b964d6ee"),
                            Bio = "Data scientist specializing in machine learning and data visualization with over 8 years of experience.",
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            FirstName = "Scarlett",
                            LastName = "Johansson",
                            Photo = "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/4/2023_4$largeimg_1660471345.jpg"
                        },
                        new
                        {
                            Id = new Guid("51e2a11b-d2fc-4822-ad0b-289099fd7fa7"),
                            Bio = "Digital marketing guru with a focus on SEO and social media strategy.",
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            FirstName = "Jennifer",
                            LastName = "Aniston",
                            Photo = "https://parade.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTkwNTgxMDQyODUzMTkyODI5/jennifer-aniston-through-the-years.webp"
                        },
                        new
                        {
                            Id = new Guid("2c978901-e3ab-4e16-8f22-9693ee02da59"),
                            Bio = "Renowned graphic designer with a passion for typography and brand identity.",
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            FirstName = "Margot",
                            LastName = "Robbie",
                            Photo = "https://media.vanityfair.com/photos/636bc27c672701552ac8f48b/master/w_1600,c_limit/1222_Margot_Robbie_embed02.jpg"
                        },
                        new
                        {
                            Id = new Guid("d39f8ccb-be75-4f68-99a1-0770be8aceb3"),
                            Bio = "Project management professional with extensive experience preparing candidates for the PMP® certification.",
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            FirstName = "Emma",
                            LastName = "Watson",
                            Photo = "https://image.tmdb.org/t/p/original/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg"
                        },
                        new
                        {
                            Id = new Guid("0672e9d3-5768-4bb0-92c2-03be4af6ebf2"),
                            Bio = "Natalie Portman, a renowned actress and passionate environmentalist, brings her wealth of knowledge and experience to the realm of sustainable living. With a strong belief in the power of renewable energy solutions, she has dedicated herself to advocating for a greener planet. Her courses are rich with practical insights on how to incorporate sustainable practices into daily life, drawing from her own journey towards living sustainably. Natalie's dedication to environmental activism is matched by her ability to inspire and engage her students. Through her comprehensive approach, she explores the various dimensions of sustainability, from green building techniques to sustainable agriculture. Her engaging teaching style combines theory with real-world applications, making her classes both informative and transformative. Natalie encourages her students to think critically about their environmental impact and empowers them to make meaningful changes. Her vision is to create a community of learners who are equipped to lead the way in sustainable living. With Natalie as your guide, you'll embark on a journey to understand the importance of sustainability and how you can be a part of the solution. Join her to discover the practices that will not only benefit the environment but also enhance your quality of life.",
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            FirstName = "Natalie",
                            LastName = "Portman",
                            Photo = "https://facts.net/wp-content/uploads/2023/07/46-facts-about-natalie-portman-1690804650.jpg"
                        },
                        new
                        {
                            Id = new Guid("fef23629-deaf-42c8-a0c4-300f402a9864"),
                            Bio = "Anne Hathaway, with her deep passion for technology and education, spearheads our Introduction to Robotics course. Having spent years in the field of robotics engineering, Anne brings a wealth of practical knowledge and hands-on experience. Her course is designed to demystify the complex world of robotics and make it accessible to everyone, from beginners to more experienced enthusiasts. Anne's approach to teaching is deeply rooted in the belief that everyone has the potential to innovate. Through her engaging lectures and interactive workshops, students are encouraged to build and program their own robots, learning not just the technical skills but also the creativity and problem-solving abilities that are essential in robotics. Anne's dedication to her students goes beyond the classroom; she is committed to creating a supportive learning environment where questions are welcomed and exploration is encouraged. Her course covers a range of topics, from the basics of Arduino and Raspberry Pi to more advanced concepts in robotics engineering. Anne's mission is to inspire her students to pursue their interests in technology and to equip them with the skills needed to thrive in this exciting field. Join Anne Hathaway in this adventure into the world of robotics and discover the endless possibilities that await.",
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            FirstName = "Anne",
                            LastName = "Hathaway",
                            Photo = "https://www.usmagazine.com/wp-content/uploads/2023/11/Anne-Hathaway-revealed-that-she-was-told-that-her-career-would-be-over-by-the-time-she-turned-35-2.jpg?w=1000&quality=86&strip=all"
                        },
                        new
                        {
                            Id = new Guid("a8403747-cc2f-4fd4-baef-30188ffd5fb7"),
                            Bio = "Penelope Cruz, an acclaimed actress with a rich background in language arts, has transitioned her passion into teaching Spanish to beginners. Her journey with languages began early in her career, allowing her to perform in a variety of roles across different cultures. Penelope's course, 'Spanish for Beginners: Master Basic Conversations', is a reflection of her love for the Spanish language and her desire to share it with others. Through her engaging teaching methods, Penelope emphasizes practical conversation skills, ensuring students gain confidence in their abilities to communicate. Her approach to teaching is infused with cultural insights, making learning a language not just about words but about understanding and appreciating a rich and vibrant culture. Penelope's classes are interactive and filled with real-life scenarios that prepare students for everyday conversations. With over a decade of experience in the film industry and numerous roles that required language mastery, Penelope brings authenticity and depth to her lessons. Her goal is to inspire a love for the Spanish language in her students, just as she has experienced in her travels and career. Join Penelope Cruz on this linguistic journey and unlock the door to new opportunities and connections through the beauty of the Spanish language.",
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            FirstName = "Penélope",
                            LastName = "Cruz",
                            Photo = "https://i.abcnewsfe.com/a/2e0c575c-cc96-480d-86a9-77f29924ac05/penelope-cruz-rt-gmh-240118_1705590269793_hpMain.jpg"
                        },
                        new
                        {
                            Id = new Guid("5479a79a-7917-40e7-adad-5389896692b0"),
                            Bio = "Meryl Streep, an icon of the silver screen, brings her unparalleled experience and insight to the world of mental health first aid. With a career that spans decades and roles that have touched on a myriad of human experiences, Meryl is uniquely positioned to lead a course on supporting others and yourself in times of mental health crises. Her course, 'Mental Health First Aid: Supporting Others and Yourself', draws upon her deep understanding of the human psyche, explored through her diverse roles. Meryl's approach to teaching is compassionate and informed, aiming to destigmatize mental health issues and provide practical support techniques. She advocates for empathy, understanding, and direct action in assisting those facing mental health challenges. The course covers recognizing signs of mental health problems, offering initial help, and guiding someone towards appropriate care. Meryl's passion for mental health awareness is palpable in her lectures, making her an inspiring figure for those looking to make a difference. With her guidance, students learn not only how to help others but also the importance of self-care and resilience. Enroll in Meryl Streep's course to embark on a meaningful journey towards becoming a supportive presence in the lives of those around you.",
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            FirstName = "Meryl",
                            LastName = "Streep",
                            Photo = "https://www.maconferenceforwomen.org/wp-content/uploads/sites/4/2017/04/meryl-streep.jpg"
                        },
                        new
                        {
                            Id = new Guid("ad8b22f8-6a5d-49e3-b3e8-27305ac66f39"),
                            Bio = "Lupita Nyong'o, an Oscar-winning actress known for her profound and emotionally resonant performances, turns her talents to the art of storytelling through creative writing. With a history of roles that span diverse narratives and cultures, Lupita brings a unique perspective to her course, 'Creative Writing: Unleash Your Imagination'. She focuses on helping students unlock their creative potential, encouraging them to explore their own stories with depth, empathy, and originality. Lupita's teaching method is deeply interactive, involving students in exercises that challenge them to think critically and creatively. Her lessons delve into character development, plot structuring, and the nuances of language, all while fostering an environment of support and inspiration. Lupita believes that everyone has a story to tell and that the act of writing can be a powerful tool for self-expression and reflection. Her passion for storytelling is infectious, making her classes a vibrant space for aspiring writers. Whether you're looking to write your first short story or embark on a novel, Lupita Nyong'o's course offers the guidance, inspiration, and techniques to help you navigate the journey of creative writing.",
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            FirstName = "Lupita",
                            LastName = "Nyong'o",
                            Photo = "https://lh3.googleusercontent.com/vDTbynIYVfDFAT5NXckaRIKpMbO2N7bn_Gb57_1k26vPDbmjwjWgnx22AwRQpl6pCtHxOo1xiNOlUdBjascfRQEk9Oadz2aJSeZvFp2e"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d34a7534-5dbc-4415-9ea0-df212d4fc1b3"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "Getting started with Node.js, Express, and MongoDB. Installation and environment setup for full stack development.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Setting Up Your Development Environment"
                        },
                        new
                        {
                            Id = new Guid("e8085833-05e9-4a7d-8237-22b025c713cf"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "Introduction to React and its core principles. Building a simple application to understand components, state, and props.",
                            Duration = 180,
                            StartDate = new DateTime(2024, 1, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Building Your First React Application"
                        },
                        new
                        {
                            Id = new Guid("633cd29b-83e4-4351-9380-f07f6b8422e7"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "Creating a seamless connection between React and Node.js. Understanding REST APIs and integrating MongoDB for data storage.",
                            Duration = 150,
                            StartDate = new DateTime(2024, 1, 26, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Connecting Frontend with Backend"
                        },
                        new
                        {
                            Id = new Guid("e14acfa0-ac64-4781-94d1-b0c3df6f7c6c"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "An introduction to Python for data manipulation and analysis. Covering NumPy, pandas, and matplotlib libraries.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 2, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python Programming for Data Science"
                        },
                        new
                        {
                            Id = new Guid("1e336063-c642-4b81-856f-767fe51a9b6a"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Exploring linear regression, logistic regression, and clustering techniques using the Scikit-learn library.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 2, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning Models with Scikit-learn"
                        },
                        new
                        {
                            Id = new Guid("30ba4b4c-4c76-4270-b9ac-f7eb71c5e01d"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "An overview of neural networks and deep learning. Implementing a basic neural network using TensorFlow.",
                            Duration = 180,
                            StartDate = new DateTime(2024, 3, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deep Learning Introduction with TensorFlow"
                        },
                        new
                        {
                            Id = new Guid("c3f3f88c-ace6-4c48-be25-3bff8c09b2b5"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Diving deep into the world of search engine optimization, understanding keywords, and optimizing your website for Google.",
                            Duration = 100,
                            StartDate = new DateTime(2024, 3, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding SEO"
                        },
                        new
                        {
                            Id = new Guid("04c445cd-dcad-4770-8592-e733ed63cd8d"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Creating and managing pay-per-click campaigns on Google Ads and social media platforms.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 3, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Effective PPC Campaigns"
                        },
                        new
                        {
                            Id = new Guid("06093e9a-2f6f-41b3-8b50-d10b9c01cc2e"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Leveraging social media platforms to enhance brand visibility and engagement. Strategies for content creation and distribution.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Social Media Marketing and Branding"
                        },
                        new
                        {
                            Id = new Guid("2c8e5628-9015-427b-9f63-b84d9bf7bb62"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "An exploration of color psychology, color palettes, and the importance of typography in design.",
                            Duration = 110,
                            StartDate = new DateTime(2024, 4, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Basics of Design: Color Theory and Typography"
                        },
                        new
                        {
                            Id = new Guid("2bfc7b68-df08-4c55-b351-d19bf9a43617"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "Mastering the basics of Adobe Photoshop for photo editing and graphic creation.",
                            Duration = 180,
                            StartDate = new DateTime(2024, 5, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Adobe Photoshop Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("08bf81b8-f5c3-480f-9c6d-af142578172b"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "Designing impactful visuals for websites, social media, and printed materials.",
                            Duration = 140,
                            StartDate = new DateTime(2024, 5, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Creating Effective Visuals for Web and Print"
                        },
                        new
                        {
                            Id = new Guid("77c6b23a-23ea-44a5-8eac-123d88b882cd"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Understanding the PMBOK framework and the process groups and knowledge areas of project management.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 6, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Project Management Framework"
                        },
                        new
                        {
                            Id = new Guid("6445ff12-447c-46eb-9e37-de066ffe233b"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Identifying, analyzing, and responding to project risks to minimize their impact.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 6, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Risk Management and Mitigation"
                        },
                        new
                        {
                            Id = new Guid("aa60b73c-309a-43f3-981d-dda4914127f9"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Techniques for creating realistic project schedules and ensuring timely project delivery.",
                            Duration = 150,
                            StartDate = new DateTime(2024, 6, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Project Scheduling and Time Management"
                        },
                        new
                        {
                            Id = new Guid("8c9c5d85-357b-4534-bc3d-bf808bee4471"),
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            Description = "An introduction to the different types of renewable energy sources and their impact on sustainable living.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Renewable Energy Basics"
                        },
                        new
                        {
                            Id = new Guid("832ca540-9464-4c07-aa5e-094c0a96e7af"),
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            Description = "Exploring the principles of green building and sustainable design in modern architecture.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 6, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Green Building Design"
                        },
                        new
                        {
                            Id = new Guid("126a1e12-d80f-4e9e-b905-68e8bf0ad349"),
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            Description = "Understanding sustainable farming practices and how they contribute to food security and environmental health.",
                            Duration = 105,
                            StartDate = new DateTime(2024, 7, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sustainable Agriculture Techniques"
                        },
                        new
                        {
                            Id = new Guid("c03cc323-fcb9-40e7-a0b4-4f9740c8fee5"),
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            Description = "Step-by-step guidance on creating a simple robot, focusing on the basics of mechanical design and programming.",
                            Duration = 180,
                            StartDate = new DateTime(2024, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Building Your First Robot"
                        },
                        new
                        {
                            Id = new Guid("d378a858-27c0-4975-90e3-b26569db3b31"),
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            Description = "Introduction to programming with Arduino, including sensor integration and basic robotics control.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 7, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Arduino Programming Basics"
                        },
                        new
                        {
                            Id = new Guid("2c598d8b-d425-413a-b169-e879fa04e93a"),
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            Description = "Exploring more complex robotics projects using Raspberry Pi, focusing on IoT applications.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 7, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Advanced Robotics with Raspberry Pi"
                        },
                        new
                        {
                            Id = new Guid("37424c57-8054-4733-b973-f5307da832dd"),
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            Description = "Learning common phrases and expressions to start speaking Spanish in daily situations.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 7, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Basic Spanish Conversation"
                        },
                        new
                        {
                            Id = new Guid("92610322-ba68-4d0e-8e33-39500f85b1ff"),
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            Description = "Covering the foundational grammar needed to build sentences and communicate effectively in Spanish.",
                            Duration = 75,
                            StartDate = new DateTime(2024, 8, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grammar Essentials"
                        },
                        new
                        {
                            Id = new Guid("249df054-2ef6-4e5a-97fe-bc1a6a03509e"),
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            Description = "Understanding the cultural nuances and expressions that are unique to the Spanish language.",
                            Duration = 60,
                            StartDate = new DateTime(2024, 8, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spanish Culture and Expressions"
                        },
                        new
                        {
                            Id = new Guid("a4106731-4c64-4e17-90c6-e8a4539c17b1"),
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            Description = "An overview of mental health, including common conditions and the importance of mental wellbeing.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 8, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding Mental Health"
                        },
                        new
                        {
                            Id = new Guid("60adcec9-8d80-469d-a965-ebd601bb800b"),
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            Description = "Techniques for providing immediate, short-term help to individuals experiencing a mental health crisis.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 8, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crisis Intervention Strategies"
                        },
                        new
                        {
                            Id = new Guid("4a0a6230-0558-48a7-ad77-b3e1fcf9191c"),
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            Description = "Strategies for raising awareness and reducing stigma associated with mental health issues.",
                            Duration = 75,
                            StartDate = new DateTime(2024, 9, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Promoting Mental Health Awareness"
                        },
                        new
                        {
                            Id = new Guid("fad26f87-054b-4d65-9f51-e6b53cd91450"),
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            Description = "Exploring the key elements of creative writing, including narrative structure, character development, and voice.",
                            Duration = 120,
                            StartDate = new DateTime(2024, 9, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fundamentals of Creative Writing"
                        },
                        new
                        {
                            Id = new Guid("2fcd8fe2-4b5d-4cc7-949a-6fa5ef7054dd"),
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            Description = "Techniques for creating complex, believable characters that engage readers.",
                            Duration = 90,
                            StartDate = new DateTime(2024, 9, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crafting Compelling Characters"
                        },
                        new
                        {
                            Id = new Guid("ba9c80c4-e4ba-4686-a36a-0ba1b4f2660b"),
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            Description = "Mastering the art of storytelling, focusing on plot development and the emotional journey of the characters.",
                            Duration = 105,
                            StartDate = new DateTime(2024, 9, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Art of Storytelling"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15aaafb9-682b-4bfe-8fc9-7262e417e652"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "An incredibly comprehensive course that offered deep insights into full stack development with practical projects. Highly recommend for beginners and intermediate developers.",
                            Rating = 9,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("f479d51b-12a8-4f50-a38e-02229cce8194"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "This course was detailed with plenty of hands-on exercises. However, some prerequisites in JavaScript would have been helpful to mention for absolute beginners.",
                            Rating = 8,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("11fb3787-756b-48f0-a06b-3b9377e47aea"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Outstanding content and delivery on complex topics. The practical sessions were particularly beneficial. A must-take course for aspiring data scientists.",
                            Rating = 10,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("3b9b1085-55b2-4b01-814f-56e08021fb35"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Provides a robust foundation in data science. The course pace is fast but manageable. Python knowledge is a must to keep up.",
                            Rating = 9,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("099df245-9d93-4dec-9ea7-aeb2d060c094"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Covers all the basics of digital marketing. Some topics could use more depth, but overall a good starter course.",
                            Rating = 7,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("a3110540-3eae-4395-9203-377b89109390"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Great insights into digital marketing trends and tools. I particularly enjoyed the case studies and practical examples.",
                            Rating = 8,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("63e2072f-004b-49fe-a187-5fbc9ee25e11"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "A fascinating journey through the basics of graphic design. The course is well-structured, engaging, and creatively stimulating.",
                            Rating = 9,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("01b1449a-da49-4dcf-a7f5-b46cd5b4997b"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "Solid introduction to graphic design principles. Would appreciate more advanced modules for further learning.",
                            Rating = 8,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("954bb649-d478-4812-b31d-8889d8024036"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "The course does an excellent job preparing for the PMP exam with detailed materials and practice questions. Some lessons felt a bit dry.",
                            Rating = 8,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("17252a75-3d04-4a9f-96d3-dc5c6647e8fc"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Provides a comprehensive overview of project management principles. Would benefit from more interactive content to keep the engagement high.",
                            Rating = 7,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("2231b420-d84a-4aa6-9429-1f9be6af4a35"),
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            Description = "Inspirational course that offers practical advice on living more sustainably. It's comprehensive and thought-provoking.",
                            Rating = 10,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("278a17ed-d393-474f-b45a-ac06fd9c9072"),
                            CourseId = new Guid("ae35af86-a051-46f0-9aef-980d4e7585ac"),
                            Description = "A great introduction to sustainability. It covers a wide range of topics and provides actionable steps to make a difference.",
                            Rating = 9,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("ac74c63e-13c3-40bd-a2d8-d28e3c036c32"),
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            Description = "Engaging and hands-on introduction to robotics. While some technical aspects can be challenging, the course is extremely rewarding.",
                            Rating = 8,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("7ef7caa9-9ee2-43a0-8902-9bfe33b63a6e"),
                            CourseId = new Guid("c65ee8c7-189a-4730-9171-d89324a534de"),
                            Description = "A good foundational course in robotics that could be improved by updating some of the course materials and resources.",
                            Rating = 7,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("81e38522-283a-43fa-9c53-d320ac700856"),
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            Description = "Excellent course for beginners. The interactive exercises and practical conversation practice were very helpful.",
                            Rating = 9,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("39393062-cad4-4b38-9b30-5355945505e5"),
                            CourseId = new Guid("f7b36bbc-397a-411d-b15c-b51355eb4465"),
                            Description = "A solid introduction to Spanish that makes learning a new language less daunting. More advanced follow-up courses would be appreciated.",
                            Rating = 8,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("982d8f63-3e7b-4cf0-bd25-8215b56e5b3a"),
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            Description = "Extremely valuable course offering crucial insights into mental health support. Highly recommended for everyone.",
                            Rating = 10,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("204b0e48-8f0a-4d50-aa43-bde3da67c8e2"),
                            CourseId = new Guid("78a56892-9dba-42cf-9328-e2cf026a5b97"),
                            Description = "Important and timely content that's presented in an accessible way. This course is essential for anyone looking to understand more about mental health.",
                            Rating = 9,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        },
                        new
                        {
                            Id = new Guid("b64f0956-b6b1-462b-a387-7fad8135e075"),
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            Description = "This course was a journey of discovery into the art of storytelling. The prompts and feedback helped me grow my writing in ways I hadn't imagined.",
                            Rating = 9,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("3f298487-e0ab-4961-888f-e8eaeae8031a"),
                            CourseId = new Guid("6d38c7e6-84eb-411c-a528-53caecbdf5a5"),
                            Description = "A great primer for aspiring writers, packed with engaging exercises and insightful tips. More content on novel writing would be beneficial.",
                            Rating = 8,
                            UserId = "2d64777e-f833-4eca-803b-8eb1b0670a5c"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0afe2b81-40c4-4ae7-9ebd-0ccaa1b0b64f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "23ddf766-a9b9-44b4-878f-e2e7b1645ac3",
                            Email = "guest1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST1@GMAIL.COM",
                            NormalizedUserName = "guest1",
                            PasswordHash = "AQAAAAEAACcQAAAAEKrdr1Zs5EJrw3b2Bv+nzkSMUQSvMIWnGQHj32/Ubq394O1WYfz7n3Me3pvRCVu/8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3fb9306-3d92-4794-b96b-7eccf681bd23",
                            TwoFactorEnabled = false,
                            UserName = "guest1"
                        },
                        new
                        {
                            Id = "6b79f761-5a4e-4457-a53b-cfc7c36ab084",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adb7b306-56c2-45b9-aab9-21ef7edd94ed",
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "user1",
                            PasswordHash = "AQAAAAEAACcQAAAAEKpPumG0iHs8ck7Btl9olhB8w9iShstULX3MCD0wAJ7wh9ze/uq9WUu/8GjJgjccVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "110c9fac-7353-4bcf-81a3-683fde9eb9b0",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "6c3438cd-8332-4e95-9a5e-adb64ec972d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f6b200d-937e-4100-af4c-7eb4e9146f44",
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "user2",
                            PasswordHash = "AQAAAAEAACcQAAAAEAIo16uV9CtC8+EUecE/775HyPRcEMnT13rnTNWGY8d6UGo1G/bEhXBtgANcj4I9/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56ac2269-7413-4f56-b36b-3c4c27865edd",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "addd0c13-6a3f-4706-afc8-219f5e89badd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e01fc90c-6c6b-4692-bbe5-46d698e97dc5",
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "user3",
                            PasswordHash = "AQAAAAEAACcQAAAAEMC1FxBOMdsgM9j0EF4w6g1oC3vogMZFbaffqrgOubiJSvNWu0Dp5kz+16nU90ujgw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "061b728b-8028-4f04-aa9a-228d3c4fcdb0",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "2d64777e-f833-4eca-803b-8eb1b0670a5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e473b7c3-afe8-4df9-b48e-8f0ebfafda95",
                            Email = "admin1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@GMAIL.COM",
                            NormalizedUserName = "admin1",
                            PasswordHash = "AQAAAAEAACcQAAAAEJkDdpzBmpjcQFFZ+EVclzFgn2LqmoR05+7HvPrhHkPwMYyNlpg8KrY6OZUREzULOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea68770f-5fec-4337-8ff0-d9be7a0d42b8",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.UserCourse", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Instructor", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithOne("Instructor")
                        .HasForeignKey("TheProject.Infrastructure.Data.Models.Instructor", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Lecture", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.UserCourse", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("UsersCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.Navigation("Instructor")
                        .IsRequired();

                    b.Navigation("Lectures");

                    b.Navigation("Reviews");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UsersCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
