// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheProject.Infrastructure.Data;

#nullable disable

namespace TheProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240328224307_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology and Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Business and Entrepreneurship"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Creative Arts and Design"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interested")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            CategoryId = 1,
                            Description = "Learn to build scalable web applications using React, Node.js, Express, and MongoDB.",
                            EndDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://img-b.udemycdn.com/course/750x422/2715276_2923_2.jpg",
                            Interested = 120,
                            StartDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Full Stack Web Development"
                        },
                        new
                        {
                            Id = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            CategoryId = 1,
                            Description = "Dive into data science and machine learning with Python, exploring data visualization, machine learning models, and more.",
                            ImageUrl = "https://media.geeksforgeeks.org/wp-content/uploads/20210629202956/DataV.png",
                            Interested = 150,
                            StartDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Science and Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            CategoryId = 2,
                            Description = "Master digital marketing tools and strategies, including SEO, PPC, social media, and content marketing.",
                            EndDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://www.redbricksmedia.com/wp-content/uploads/2023/04/What-are-the-Advantages-of-Digital-Marketing.jpg",
                            Interested = 90,
                            StartDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Digital Marketing Essentials"
                        },
                        new
                        {
                            Id = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            CategoryId = 3,
                            Description = "Explore the fundamentals of graphic design, including layout, composition, typography, and color theory.",
                            ImageUrl = "https://i.ytimg.com/vi/YqQx75OPRa0/maxresdefault.jpg",
                            Interested = 110,
                            StartDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            CategoryId = 2,
                            Description = "Prepare for the PMP certification exam with this comprehensive course covering project management best practices.",
                            EndDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://play-lh.googleusercontent.com/KO4qR1Yik54zkBEWKoVqbUtJqOAw2w6loHapeAaacDeBpy9lU7hM1fpNU-VN4kzRwpc",
                            Interested = 75,
                            StartDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Project Management Professional Certification Prep"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9eda2f0b-b708-4038-8f38-245444f5c9bf"),
                            Bio = "Expert in full stack development with over 10 years of experience.",
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            FirstName = "Angelina",
                            LastName = "Jolie",
                            Photo = "https://i.pinimg.com/736x/b7/5b/49/b75b49e64989d5b5944c80f302228e2e.jpg"
                        },
                        new
                        {
                            Id = new Guid("bd6cf82d-a7b0-4b32-a660-a99f905e6a0a"),
                            Bio = "Data scientist specializing in machine learning and data visualization with over 8 years of experience.",
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            FirstName = "Scarlett",
                            LastName = "Johansson",
                            Photo = "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/4/2023_4$largeimg_1660471345.jpg"
                        },
                        new
                        {
                            Id = new Guid("d1ce4566-c33c-4534-977b-e964e6244f4b"),
                            Bio = "Digital marketing guru with a focus on SEO and social media strategy.",
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            FirstName = "Jennifer",
                            LastName = "Aniston",
                            Photo = "https://parade.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTkwNTgxMDQyODUzMTkyODI5/jennifer-aniston-through-the-years.webp"
                        },
                        new
                        {
                            Id = new Guid("d8736e7c-a217-4aae-92d9-f7c1a1ffdc76"),
                            Bio = "Renowned graphic designer with a passion for typography and brand identity.",
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            FirstName = "Margot",
                            LastName = "Robbie",
                            Photo = "https://media.vanityfair.com/photos/636bc27c672701552ac8f48b/master/w_1600,c_limit/1222_Margot_Robbie_embed02.jpg"
                        },
                        new
                        {
                            Id = new Guid("15eddde4-7a5d-4f6e-97d7-f9378e880da7"),
                            Bio = "Project management professional with extensive experience preparing candidates for the PMP® certification.",
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            FirstName = "Emma",
                            LastName = "Watson",
                            Photo = "https://image.tmdb.org/t/p/original/A14lLCZYDhfYdBa0fFRpwMDiwRN.jpg"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33b60157-9b69-4dbd-89aa-8c68f7fe34a7"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "Understanding the basics of web development with HTML and CSS.",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            StartDate = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to HTML and CSS"
                        },
                        new
                        {
                            Id = new Guid("8ebcefae-69f7-46d7-8f88-981e381f5850"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "Interactive web pages with JavaScript.",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            StartDate = new DateTime(2024, 1, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "JavaScript and the Web"
                        },
                        new
                        {
                            Id = new Guid("ba0ba8c2-8d6f-4127-a070-9f2baa1327e7"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Introduction to Python and its libraries for data science.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            StartDate = new DateTime(2024, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python for Data Science"
                        },
                        new
                        {
                            Id = new Guid("73472ee4-a2a6-456c-9535-00a3ce027c40"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Analyzing data sets to summarize their main characteristics.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            StartDate = new DateTime(2024, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Exploratory Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("377bad54-86b4-4cab-9bca-ed5fd94740e7"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Learn the basics of Search Engine Optimization to increase your website visibility.",
                            Duration = new TimeSpan(0, 1, 15, 0, 0),
                            StartDate = new DateTime(2024, 3, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SEO Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("ce51626c-b74c-44ef-a73b-8fc494905789"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Effective strategies for engaging with your audience on social media platforms.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            StartDate = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Social Media Marketing Strategies"
                        },
                        new
                        {
                            Id = new Guid("1b55d95c-e3fb-42a5-b493-8dc990ae9778"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "A deep dive into the core principles of graphic design, focusing on composition and layout.",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            StartDate = new DateTime(2024, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Principles: Composition and Layout"
                        },
                        new
                        {
                            Id = new Guid("cb915ba6-4f59-4e01-a4ed-8002d0ca83e6"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "Exploring the role of typography in graphic design and how to use it effectively.",
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            StartDate = new DateTime(2024, 5, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Typography in Design"
                        },
                        new
                        {
                            Id = new Guid("2e683944-e760-4a78-8841-35bfe9ea0ba7"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Covering the fundamental concepts and terminologies of project management.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            StartDate = new DateTime(2024, 6, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Project Management Basics"
                        },
                        new
                        {
                            Id = new Guid("4da4bff7-6f94-498d-84f2-100fa3c91d36"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "Strategies and tips for tackling the PMP certification exam.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            StartDate = new DateTime(2024, 6, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Preparing for the PMP Exam"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb0485b4-1710-42d6-a0f4-980bee02e48b"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "A comprehensive course that offers deep insights into full stack development.",
                            Rating = 8,
                            UserId = "6b79f761-5a4e-4457-a53b-cfc7c36ab084"
                        },
                        new
                        {
                            Id = new Guid("482c02ef-7903-4d8e-8779-1abfef65f7b8"),
                            CourseId = new Guid("6663d89a-3f07-4bea-b4f4-dc8b47efe599"),
                            Description = "Excellent course on data science. Highly recommend for beginners and intermediates.",
                            Rating = 9,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("141bee25-c82f-4792-9682-f98421473072"),
                            CourseId = new Guid("412588b2-b00f-49dc-b261-04b65edfd9f3"),
                            Description = "Great insights into digital marketing strategies. Useful for all levels.",
                            Rating = 7,
                            UserId = "6c3438cd-8332-4e95-9a5e-adb64ec972d6"
                        },
                        new
                        {
                            Id = new Guid("d6588c27-e694-4061-894d-eb5c96718e8f"),
                            CourseId = new Guid("557a4fcd-1f84-4487-a7bd-8240327c976b"),
                            Description = "Loved the practical approach to graphic design principles. The examples were very helpful.",
                            Rating = 6,
                            UserId = "addd0c13-6a3f-4706-afc8-219f5e89badd"
                        },
                        new
                        {
                            Id = new Guid("8a81b013-16b0-4534-9250-4faa26f79d41"),
                            CourseId = new Guid("f5b840fe-cd8b-44e1-8c5e-5cdbec1d4a0f"),
                            Description = "The PMP prep course was detailed and well-structured. It helped me pass the exam on the first try.",
                            Rating = 8,
                            UserId = "addd0c13-6a3f-4706-afc8-219f5e89badd"
                        },
                        new
                        {
                            Id = new Guid("557e40f9-9962-4b60-bb63-28218fe0f22f"),
                            CourseId = new Guid("9f9f3e8b-8fdd-4a38-b052-a5109123e2ab"),
                            Description = "This course exceeded my expectations! The content was clear, and the projects were both challenging and rewarding.",
                            Rating = 10,
                            UserId = "addd0c13-6a3f-4706-afc8-219f5e89badd"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0afe2b81-40c4-4ae7-9ebd-0ccaa1b0b64f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83052185-75c0-43c7-b9ea-4cc61bed4434",
                            Email = "guest1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST1@GMAIL.COM",
                            NormalizedUserName = "guest1",
                            PasswordHash = "AQAAAAEAACcQAAAAELgVRHyj1UerriLx7E4l6yJv/ODJ/6ybVaZ71V4N4wSiA19dWNTrCnLiFq7aswGEfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47ff3e18-11a6-4cbf-926f-9a0f987b82e4",
                            TwoFactorEnabled = false,
                            UserName = "guest1"
                        },
                        new
                        {
                            Id = "6b79f761-5a4e-4457-a53b-cfc7c36ab084",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ad3fd9b-4c77-4cdc-928a-ae8e9e24fcf8",
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "user1",
                            PasswordHash = "AQAAAAEAACcQAAAAENNVhxWKXB/s2pm5ZmZdqolF5CZyYQSjb8C40Pko6ZV5tqBwN8yuRaQbndLDFDY3aw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "264cad39-bb5b-4b6f-afb0-871cdbef9645",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "6c3438cd-8332-4e95-9a5e-adb64ec972d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bae1be2-f14f-446a-9c6d-3faea06127fb",
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "user2",
                            PasswordHash = "AQAAAAEAACcQAAAAEOPjot7rbkQfqSBJtXjpOtEsYLMMRZrBmO418W2Cd9q5HHj6YilwzP4IgVCImi4hFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77fb9c30-22e8-40dc-8543-a0943e2f6709",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "addd0c13-6a3f-4706-afc8-219f5e89badd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9bdd2bc8-58cb-4f8f-964b-d6812baaeaf3",
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "user3",
                            PasswordHash = "AQAAAAEAACcQAAAAEFWWqE+7zBThjwUXHXlMDSCU9adUYgPnzHj5ExSoBkpUi6B63/15nmm2LmlHhS3rVQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30421e61-085a-478d-950e-da48b6fbd6f4",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "2d64777e-f833-4eca-803b-8eb1b0670a5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70e5d5fd-1c13-40ae-abd7-b826f29a03fb",
                            Email = "admin1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@GMAIL.COM",
                            NormalizedUserName = "admin1",
                            PasswordHash = "AQAAAAEAACcQAAAAEJnMAihpF6mrBaqd15HGBu62bdHp0niA7x1WpeYJ+nTkZNTaw/VgyR+OBD1PkSk/ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4054a77f-53ec-4829-9b53-69cb38bc72e4",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        });
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.UserCourse", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Instructor", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithOne("Instructor")
                        .HasForeignKey("TheProject.Infrastructure.Data.Models.Instructor", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Lecture", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.UserCourse", b =>
                {
                    b.HasOne("TheProject.Infrastructure.Data.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheProject.Infrastructure.Data.Models.User", "User")
                        .WithMany("UsersCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.Course", b =>
                {
                    b.Navigation("Instructor")
                        .IsRequired();

                    b.Navigation("Lectures");

                    b.Navigation("Reviews");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("TheProject.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UsersCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
